services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sql-server
    ports:
      - "14330:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sql_Server_Password
      - MSSQL_PID=Standard
    volumes:
      - ./sql_server_data:/var/opt/mssql
    restart: always

  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--requirepass redis_password
    volumes:
      - ./redis_data:/data
    restart: always